---
  - name: "install python for Ansible."
    become: true
    apt:
      name: ["python3"]
      state: latest
      update_cache: yes

  - name: Update apt
    become: true
    apt: 
      update_cache: yes

  - name: Upgrade apt
    become: true
    apt: 
      upgrade: 'yes'

  - name: Remove redundant dependencies
    become: true
    apt:
      autoremove: yes
      
  - name: Export env variables
    become: yes  
    shell:  |    
      touch /etc/profile.d/env.sh
      . ~/.bashrc