---
- name: Download AWS CLI
  get_url:
    url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
    dest: "/tmp/awscli.zip"

- name: Unzip downloaded AWS CLI
  unarchive:
    src: "/tmp/awscli.zip"
    dest: "/usr/local/awscli"
    remote_src: yes
    creates: "/usr/local/awscli/aws"

- name: Install AWS CLI
  command: /usr/local/awscli/aws/install.sh