---
- name: Download AWS CLI
  get_url:
    url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
    dest: "/tmp/awscli.zip"

- name: Unzip downloaded AWS CLI
  unarchive:
    src: "/tmp/awscli.zip"
    dest: "./"
    args:
      chdir: $HOME

- name: Install AWS CLI
  command: ./awscli/aws/install
  args:
    chdir: $HOME