---
- name: "Download AWS CLI"
  shell: curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
  args:
    chdir: $HOME

- name: "Download kubectl"
  shell: curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.19.6/2021-01-05/bin/linux/amd64/kubectl
  args:
    chdir: $HOME

- name: "Unzip the AWS CLI Archive"
  shell: unzip awscliv2.zip
  args:
    chdir: $HOME

- name: "Install AWS CLI"
  shell: ./aws/install
  args:
    chdir: $HOME

- name: "Change permissions"
  shell: chmod +x ./kubectl
  args:
    chdir: $HOME

- name: "Copy file"
  shell: mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin
  args:
    chdir: $HOME

- name: "Add $HOME/bin path to the bashrc"
  shell: echo 'export PATH=$PATH:$HOME/bin' >> .bashrc
  args:
    chdir: $HOME
