version: 2.1

jobs:
 
  test:
    docker:
      # Use the same Docker base as the project
      - image: python:3.9-buster

    working_directory: ~/repo

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # run lint!
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint



  docker-upload:
    
    docker:
      - image: cimg/go:1.17

    steps:
      - checkout

      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true

      - run:
          name: Build Docker image
          command: |
            DOCKER_PATH=leopoldwalther/valencia-real-estate-report
            echo "Docker ID and Image: $DOCKER_PATH"

            docker build --tag=valencia-real-estate-report .

            # Authenticate & tag
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker tag valencia-real-estate-report $DOCKER_PATH:latest

            # Push image to a docker repository
            docker push $DOCKER_PATH:latest
            
  deploy-eks-cluster:
    docker:
      - image: circleci/python:3.9

    steps:
      - checkout

      - run:
          name: Install AWS CLI and eksctl
          command: |
            sudo apt-get update
            sudo apt-get install -y awscli
            sudo curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | sudo tar xz -C /usr/local/bin
            sudo mv /usr/local/bin/eksctl /usr/local/bin/eksctl-$(eksctl version | awk '{print $3}')

      - run:
          name: Create EKS Cluster
          command: |
            eksctl create cluster \
              --name $EKS_CLUSTER_NAME \
              --region $AWS_DEFAULT_REGION \
              --node-type t3.medium \
              --nodes 2 \
              --managed

  
workflows:
  default: 

    jobs:
      - test
      - docker-upload:
          requires: [test]
      - deploy-eks-cluster:
          requires: [docker-upload]
      





