apiVersion: v1
kind: Service
metadata:
  name: vlc-real-estate-app-service
spec:
  selector:
    app: vlc-real-estate-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer