---

- name: Update kubernetes deployment to latest docker image
  shell: |
    kubectl set image deployment/{{ ENVIRONMENT_NAME }} {{ ENVIRONMENT_NAME }}-container={{ DOCKER_PATH }}:{{ CIRCLE_WORKFLOW_ID }}

- name: Wait for 60 seconds
  pause:
    seconds: 60

- name: Check if deployment successful
  shell: |
    kubectl rollout status deployments/{{ ENVIRONMENT_NAME }}
