 ---

- name: Create kubeconfig for cluster
  shell: |
    aws eks update-kubeconfig --region {{ AWS_DEFAULT_REGION }} --name {{ ENVIRONMENT_NAME }}-Cluster

- name: Get nodes
  shell: |
    kubectl get svc vlc-real-estate-app-service > /home/ubuntu/elb-dns.txt
  args:
    creates: /home/ubuntu/elb-dns.txt

- name: Copy the file to the local machine
  fetch:
    src: /home/ubuntu/elb-dns.txt
    dest: ./ansible/elb-dns.txt
    flat: yes
