 ---

- name: Create kubeconfig for cluster
  shell: |
    aws eks update-kubeconfig --region {{ AWS_DEFAULT_REGION }} --name {{ ENVIRONMENT_NAME }}-Cluster

- name: Get nodes
  shell: |
    kubectl get svc {{ ENVIRONMENT_NAME }}-service
  register: dns
      args:
        chdir: $HOME

- name: Copy dns
  copy:
    content: "{{ dns.stdout }}"
    dest: "~/dns.txt"
  delegate_to: localhost