Description: >
    Leopold Walther:
    This template deploys ...


Parameters:

    EnvironmentName:
      Description: Environment name that will be prefixed to resource names
      Type: String


Resources:

  EKSClusterSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow Jump Host to SSH to WebServers
      VpcId:
        Fn::ImportValue:
          !Sub "${EnvironmentName}-VPCID"
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
      - IpProtocol: tcp
        FromPort: 0
        ToPort: 80
        CidrIp: 0.0.0.0/0

  EKSClusterRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: 
        !Sub ${EnvironmentName}-EKSClusterRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - eks.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        - arn:aws:iam::aws:policy/AmazonEKSServicePolicy
        - arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess

  EKSClusterProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: 
        !Sub ${EnvironmentName}-ClusterProfile
      Path: "/"
      Roles:
        - !Ref EKSClusterRole

  EKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Version: "1.27"
      Name: !Sub ${EnvironmentName}-Cluster
      RoleArn: 
        !GetAtt EKSClusterRole.Arn
      ResourcesVpcConfig:
        SecurityGroupIds:
          - !Ref EKSClusterSecurityGroup
        SubnetIds:
          Fn::Split:
            - ","
            - Fn::ImportValue:
                Fn::Sub: ${EnvironmentName}-PUB-NETS


Outputs:

  EKSClusterId:
    Description: EKS Cluster ID
    Value: 
      !Ref EKSCluster
    Export:
      Name: 
        !Sub ${EnvironmentName}-EKSClusterId

  EKSClusterRoleArn:
    Description: Role for accessing and creating aws resources
    Value: 
      !GetAtt EKSClusterRole.Arn
    Export:
      Name: 
        !Sub ${EnvironmentName}-EKSClusterRoleArn