---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root  
  gather_facts: false
  
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
    - name: "wait 60 seconds for target connection to become reachable/usable."
      wait_for_connection:
        delay: 60
        timeout: 60

    - name: "install python for Ansible."
      become: yes
      apt:
        name: "python3-pip"
        update_cache: yes
        state: present

  # Get the environment variables from CircleCI and add to the EC2 instance 
  environment:
    ENVIRONMENT_NAME: "{{ lookup('env','ENVIRONMENT') }}" 

  roles:
    - configure-server
    - configure-prometheus-node-exporter