---
- name: Install dependencies
  hosts: web
  user: ubuntu
  become: true
  gather_facts: false

  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
    - name: Install zip
      apt:
        name: zip
        state: present

  roles:
    - configure-server

- name: Download kubeconfig
  hosts: web
  user: ubuntu
  become: true
  gather_facts: false

  vars:
    AWS_DEFAULT_REGION: "{{ lookup('env', 'AWS_DEFAULT_REGION') }}"
    AWS_ACCESS_KEY_ID: "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
    AWS_SECRET_ACCESS_KEY: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"
    ENVIRONMENT_NAME: "{{ lookup('env', 'ENVIRONMENT_NAME') }}"

  pre_tasks:
    - name: Set AWS_DEFAULT_REGION
      shell: "aws configure set default.region {{ AWS_DEFAULT_REGION }}"
    - name: Set AWS_ACCESS_KEY_ID
      shell: "aws configure set aws_access_key_id {{ AWS_ACCESS_KEY_ID }}"
    - name: Set the AWS_SECRET_ACCESS_KEY
      shell: "aws configure set aws_secret_access_key {{ AWS_SECRET_ACCESS_KEY }}"

  tasks:
    - name: Create kubeconfig for cluster
      shell: "aws eks update-kubeconfig --region {{ AWS_DEFAULT_REGION }} --name {{ ENVIRONMENT_NAME }}-Cluster"