---
- name: Install dependencies
  hosts: web
  user: ubuntu
  become: true
  gather_facts: false

  pre_tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install zip
      apt:
        name: [ "unzip" ]
        state: latest
        update_cache: yes

  roles:
    - configure-server