---

- name: Create kubeconfig for cluster
  shell: |
    aws eks update-kubeconfig --region {{ AWS_DEFAULT_REGION }} --name {{ ENVIRONMENT_NAME }}-Cluster

- name: Get nodes
  shell: |
    kubectl get nodes

- name: Copy kubernetes deployment
  copy:
    src: kubernetes-deployment.yaml
    dest: $HOME

- name: Apply kubernetes deployment
  shell: |
    kubectl apply -f kubernetes-deployment.yaml
  args:
    chdir: $HOME

#- name: Initial Deployment of App
#  shell: "kubectl create deploy vlc-real-estate-app --image={{ DOCKER_PATH }}:latest"

#- name: Wait for 60 seconds for the pod to be deployed
#  pause:
#    seconds: 60

#- name: Get pod id
#  shell: "pod=$(kubectl get pods | grep -o 'vlc-real-estate-app[^ ]*')"
  
#- name: Forward ports
#  shell: "sudo kubectl port-forward pod/{{ pod }} 80:80"


